### ISSUE TITLE
puid on client site (brainstorming task)

### ISSUE THREAD

**Issue by pid** [pid/puid#10]
http://www.w3.org/TR/http://www.w3.org/TR/hr-time//
http://www.w3.org/TR/hr-time/#sec-DOMHighResTimeStamphttps://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp
https://gist.github.com/paulirish/5438650  // polyfill
http://www.sitepoint.com/discovering-the-high-resolution-time-api/
http://updates.html5rocks.com/2012/08/When-milliseconds-are-not-enough-performance-now

created the task only as reminder.... actually I don't need it on client-side
If you have input/thoughts, feel free to contribute ;-)

**Comment by jas-** [comment]
Have you considered the limitations of [epoch](http://en.wikipedia.org/wiki/Unix_time#Notable_events_in_Unix_time)?

**Comment by pid** [comment]
Is this a quest? ;-)  2036? 2038? 2106? 
Please give me some more input,...

**Comment by jas-** [comment]
Never mind I missed `safe until 2059` in the readme.

**Comment by pid** [comment]
:+1:
