### ISSUE TITLE
PUID vs. UUID?

### ISSUE THREAD

**Issue by rse** [pid/puid#12]
I'm confused as you do not state anything about the relationships of PUIDs to UUIDs and from your PUID description I also do not see what benefit PUIDs provide over UUIDs. Can you please add some description about the relationships between PUIDs and UUIDs to your project, because UUIDs are standardized since a decade and seem to solve the same problem as PUIDs, hence it is vital to easily understand what different problem PUIDs seem to solve or why they solve the same problem better. Thanks.

**Comment by pid** [comment]
hi, 
I needed a short unique identifier in a distributed environment, **sortable**, **shorter than UUID**. 

Of course I knew UUID, but too long for my usecase and not sortable... that's the benefit of PUID... at least for me ;-) 
My usecase: keys in Redis

> Can you please add some description about the relationships between PUIDs and UUIDs to your project
coming soon ;-)
