### ISSUE TITLE
The resolution of the timestamp used for long PUID should be milliseconds

### ISSUE THREAD

**Issue by lxjuly** [pid/puid#13]
As stated in the title, you are using `Date.now()` to get the timestamp and encode it. `Date.now()` returns milliseconds based timestamp instead of microseconds

Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now

**Comment by pid** [comment]
@lxjuly Thanks 👍 fixed the docs
